In [1]:
import numpy as np
import time
import torch
import torch.optim as optim
import torch.nn.functional as F
from tqdm import tqdm

from IPython.display import clear_output

from tetris import Tetris
from tetris_master import TetrisMaster2

In [2]:
w, h = 10, 20
epoch = 1000

game = Tetris(w, h)
model = TetrisMaster2(bw=w, bh=h).double()

In [3]:
cp = torch.load('checkpoints/test_model')
model.load_state_dict(cp['model_state_dict'])

<All keys matched successfully>

In [4]:
game.clear_board()
game.set_random_state(n_cols=1)
for _ in range(100):
    clear_output(wait=True)
    # x = np.concatenate([game.board.reshape(-1), [game.next]])
    x = torch.tensor(game.board, dtype=torch.double).unsqueeze(0)
    yp, yr = model(x, torch.tensor(game.next, dtype=torch.double).view(1, 1))#[0]
#     game.clear_board()
#     d = game.set_random_state(n_cols=1)
    game.print()
    with torch.no_grad():
        col = np.random.choice(range(w), p=yp)
        rot = np.random.choice(range(4), p=yr)
        res = game.turn(col, rot)
    print(f'{res=}')
    print(yp)
    print(yr)
    time.sleep(0.5)
    

[[1 1 1 1]]
self.total_lines_burnt=1

. . . . . . . . . . 20
. . @ @ @ . . . . . 19
. . @ . @ @ . . . . 18
. . . . . @ . . . . 17
. . . . . @ @ @ . . 16
. . . . . @ @ . . . 15
. . . . . @ . . . . 14
@ @ . . . @ @ . . . 13
@ @ . . . . @ @ . . 12
@ @ . . . @ @ @ @ @ 11
@ . . . . . @ @ . . 10
@ . . . . @ @ @ . . 9
@ . . . . @ . . . . 8
@ . . . . @ . . . . 7
@ . . . . @ . . . . 6
@ . . . . @ . @ . . 5
@ @ @ . . @ . @ . . 4
@ @ @ . . @ . @ @ . 3
@ . @ @ @ @ . @ . . 2
@ . @ @ @ . . @ @ . 1
0 1 2 3 4 5 6 7 8 9
res=(-0.01, -0.0101)
tensor([0.0932, 0.0932, 0.1050, 0.0932, 0.1075, 0.1128, 0.1128, 0.0932, 0.0932,
        0.0962], dtype=torch.float64, grad_fn=<SoftmaxBackward0>)
tensor([0.2585, 0.2585, 0.2585, 0.2244], dtype=torch.float64,
       grad_fn=<SoftmaxBackward0>)


KeyboardInterrupt: 

In [ ]:
print()